[package]
name = "osiris-app"
description = "The Osiris game"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "osiris"
path = "src/main.rs"

[dependencies]
osiris-formats = { path = "../osiris-formats" }
osiris-render = { path = "../osiris-render" }
osiris-sim = { path = "../osiris-sim" }
osiris-ui = { path = "../osiris-ui" }
osiris-audio = { path = "../osiris-audio" }
wgpu = "30"
winit = "0.30"
pollster = "1"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
png = "0.18"
